apiVersion: v1
kind: Service
metadata:
  name: k8s-back
  namespace: default
spec:
  selector:
    app: k8s-back
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: php-connection
  namespace: default
spec:
  selector:
    app: k8s-db
  ports:
    - port: 3307
  clusterIP: None